# Generated by Django 4.0.4 on 2022-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название группы для отображения в списке', max_length=255, verbose_name='Название группы')),
                ('group_id', models.IntegerField(default=0, verbose_name='ID Группы')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Json данные')),
                ('user_id', models.CharField(blank=True, default=0, max_length=2, verbose_name='Тест поле для юзера')),
            ],
            options={
                'verbose_name': 'Список групп',
                'verbose_name_plural': 'Список групп',
            },
        ),
    ]
